language: python
python:
  - '2.7'
  - '3.4'
  - '3.6'
  - pypy

cache: pip

install:
  - pip install --upgrade setuptools
  - pip install -r requirements.txt

script:
  - pytest -v
  - python paramsweep.py --nbeta 2 --ngamma 2 num_results/sweep 2
  - python validate.py --t0 0.5 --h 0.1 --tau 0.005 num_results/validate 2 1